import {createHmac,timingSafeEqual,createHash} from 'node:crypto';
import {defaultPlan,validatePlan} from '../public/motion.js';
const prefix='reachrise:demo:v1:';
const redisConfig=()=>process.env.UPSTASH_REDIS_REST_URL&&process.env.UPSTASH_REDIS_REST_TOKEN?{url:process.env.UPSTASH_REDIS_REST_URL,token:process.env.UPSTASH_REDIS_REST_TOKEN}:{url:process.env.KV_REST_API_URL,token:process.env.KV_REST_API_TOKEN};
export const configured=()=>Boolean(redisConfig().url&&redisConfig().token&&process.env.AUTH_SECRET?.length>=32&&process.env.PATIENT_ACCESS_CODE?.length>=12&&process.env.THERAPIST_ACCESS_CODE?.length>=12&&process.env.PATIENT_ACCESS_CODE!==process.env.THERAPIST_ACCESS_CODE);
const emailConfigured=()=>Boolean(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM&&process.env.THERAPIST_EMAIL&&process.env.APP_URL?.startsWith('https://'));
const sign=s=>createHmac('sha256',process.env.AUTH_SECRET||'').update(s).digest('base64url');
export function token(role){const s=Buffer.from(JSON.stringify({role,exp:Date.now()+8*60*60*1000})).toString('base64url');return `${s}.${sign(s)}`}
export function verifyToken(t){try{const [s,sig,...extra]=t.split('.');if(extra.length||!safeEqual(sig,sign(s)))return null;const d=JSON.parse(Buffer.from(s,'base64url'));return ['patient','therapist'].includes(d.role)&&d.exp>Date.now()?d.role:null}catch{return null}}
function safeEqual(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb)}
async function redis(...command){const config=redisConfig();const r=await fetch(config.url,{method:'POST',headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('Storage unavailable');const d=await r.json();if(d.error)throw new Error('Storage unavailable');return d.result}
const read=async k=>{const s=await redis('GET',prefix+k);return s?JSON.parse(s):null};
const write=(k,v,...args)=>redis('SET',prefix+k,JSON.stringify(v),...args);
async function currentPlan(){return await read('plan')||{...defaultPlan}}
export function validSession(s){return s&&/^[a-f0-9-]{36}$/.test(s.id)&&['camera','simulation'].includes(s.source)&&validatePlan(s.plan)&&Number.isInteger(s.plan.version)&&Number.isInteger(s.reps)&&s.reps>=0&&s.reps<=s.plan.reps*s.plan.sets&&typeof s.completed==='boolean'&&s.completed===(s.reps===s.plan.reps*s.plan.sets)&&Number.isFinite(s.activeSeconds)&&s.activeSeconds>=0&&s.activeSeconds<=86400&&Number.isInteger(s.coverage)&&s.coverage>=0&&s.coverage<=100&&((s.min===null&&s.max===null)||(Number.isFinite(s.min)&&Number.isFinite(s.max)&&s.min>=0&&s.max<=180&&s.min<=s.max))&&Number.isFinite(Date.parse(s.startedAt))&&Number.isFinite(Date.parse(s.endedAt))&&Date.parse(s.endedAt)>=Date.parse(s.startedAt)&&Date.parse(s.endedAt)<=Date.now()+60000;}
async function notify(id){const s=await read('session:'+id);if(!s)return 'failed';if(s.notification==='accepted')return 'accepted';if(!emailConfigured()){s.notification='disabled';await write('session:'+id,s);return s.notification}if(Date.now()-Date.parse(s.endedAt)>23*3600*1000)return s.notification;
  const locked=await redis('SET',prefix+'mail-lock:'+id,'1','NX','EX',30);if(!locked)return s.notification;
  try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':'reachrise-'+id},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[process.env.THERAPIST_EMAIL],subject:'A new exercise session is ready to review',text:`A demonstration session has been added to your Reach & Rise dashboard. Sign in to review the report:\n${process.env.APP_URL}\n\nThis notification contains no patient measurements.`}),signal:AbortSignal.timeout(10000)});s.notification=r.ok?'accepted':'failed';await write('session:'+id,s);return s.notification}catch{s.notification='failed';await write('session:'+id,s);return 'failed'}finally{await redis('DEL',prefix+'mail-lock:'+id)}
}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');const send=(n,d)=>res.status(n).json(d);const url=new URL(req.url,'http://localhost'),action=url.searchParams.get('action');
try{
if(action==='config'&&req.method==='GET'){
 const cloud=configured();
 if(!cloud)console.warn('Reach & Rise configuration checks',JSON.stringify({redisUrlPresent:Boolean(redisConfig().url),redisTokenPresent:Boolean(redisConfig().token),authSecretMeetsMinimum:(process.env.AUTH_SECRET?.length||0)>=32,patientCodeMeetsMinimum:(process.env.PATIENT_ACCESS_CODE?.length||0)>=12,therapistCodeMeetsMinimum:(process.env.THERAPIST_ACCESS_CODE?.length||0)>=12,accessCodesDiffer:process.env.PATIENT_ACCESS_CODE!==process.env.THERAPIST_ACCESS_CODE}));
 return send(200,{cloud,email:emailConfigured()});
}
if(!configured())return send(503,{error:'Connected demo is not configured. Use the device-local demonstration.'});
if(!['GET','POST'].includes(req.method))return send(405,{error:'Method not allowed'});
if(req.method==='POST'){const origin=req.headers.origin;const host=req.headers['x-forwarded-host']||req.headers.host;if(!origin||new URL(origin).host!==host)return send(403,{error:'Request origin rejected'});if(!String(req.headers['content-type']).startsWith('application/json'))return send(415,{error:'JSON required'});if(JSON.stringify(req.body||{}).length>12000)return send(413,{error:'Request too large'});}
const b=req.body||{};const cookie=String(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('rr_session='));const role=cookie?verifyToken(cookie.slice(11)):null;const secure=process.env.VERCEL?' Secure;':'';
if(action==='login'&&req.method==='POST'){
 const ip=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0],bucket=createHash('sha256').update(ip).digest('hex').slice(0,24)+':'+Math.floor(Date.now()/600000),k=prefix+'login:'+bucket;
 const attempts=await redis('INCR',k);if(attempts===1)await redis('EXPIRE',k,610);if(attempts>15)return send(429,{error:'Too many attempts. Try again in 10 minutes.'});
 const expected=b.role==='patient'?process.env.PATIENT_ACCESS_CODE:b.role==='therapist'?process.env.THERAPIST_ACCESS_CODE:null;if(!expected||!safeEqual(b.code,expected))return send(401,{error:'Invalid role or access code'});
 res.setHeader('Set-Cookie',`rr_session=${token(b.role)}; HttpOnly;${secure} SameSite=Strict; Path=/; Max-Age=28800`);return send(200,{role:b.role});}
if(action==='logout'&&req.method==='POST'){res.setHeader('Set-Cookie',`rr_session=; HttpOnly;${secure} SameSite=Strict; Path=/; Max-Age=0`);return send(200,{ok:true})}
if(!role)return send(401,{error:'Please sign in again.'});
if(action==='data'&&req.method==='GET'){const ids=await redis('ZREVRANGE',prefix+'sessions',0,99);const sessions=(await Promise.all(ids.map(id=>read('session:'+id)))).filter(Boolean);return send(200,{role,plan:await currentPlan(),sessions})}
if(action==='plan'&&req.method==='POST'){if(role!=='therapist')return send(403,{error:'Only the therapist can change the program.'});if(!validatePlan(b))return send(400,{error:'Invalid exercise program'});await redis('SET',prefix+'version','1','NX');const version=await redis('INCR',prefix+'version'),p={exercise:b.exercise,side:b.side,low:b.low,high:b.high,reps:b.reps,sets:b.sets,rest:b.rest,instructions:b.instructions,version};await write('plan:'+version,p);await write('plan',p);return send(200,{plan:p})}
if(action==='session'&&req.method==='POST'){if(role!=='patient')return send(403,{error:'Only the patient can submit a session.'});if(!validSession(b))return send(400,{error:'Invalid session report'});const prescribed=b.plan.version===1?defaultPlan:await read('plan:'+b.plan.version);if(!prescribed||Object.keys(defaultPlan).some(k=>b.plan[k]!==prescribed[k]))return send(400,{error:'The report does not match its prescribed program.'});const existing=await read('session:'+b.id);if(existing&&existing.startedAt!==b.startedAt)return send(409,{error:'Session identifier already exists'});const s={id:b.id,source:b.source,plan:prescribed,startedAt:b.startedAt,endedAt:b.endedAt,reps:b.reps,completed:b.completed,activeSeconds:b.activeSeconds,coverage:b.coverage,min:b.min,max:b.max,notification:'queued'};await write('session:'+b.id,s,'NX');await redis('ZADD',prefix+'sessions',Date.parse(b.endedAt),b.id);let notification='unknown';try{notification=await notify(b.id)}catch{}return send(200,{saved:true,notification})}
if(action==='notify'&&req.method==='POST'){if(typeof b.id!=='string'||!/^[a-f0-9-]{36}$/.test(b.id))return send(400,{error:'Invalid session ID'});return send(200,{notification:await notify(b.id)})}
return send(404,{error:'Unknown action'});
}catch{return send(503,{error:'The service is temporarily unavailable. Your report has not been confirmed as saved.'})}}
